### ISSUE TITLE
global name 'address' is not defined

### ISSUE THREAD

**Issue by rchrd2** [thesis/sockfilter#1]
I seem to be one of the early adopters of this library. I think it's really useful for testing while ensuring to not hit external apis/services etc.

I ran into this issue "address" is not defined. I am able to A/B this and prove that it is this library that is causing the issue. Any ideas?

I am using a custom test case that sets up and tears down the sockfilter.

```
import sockfilter
from django.test import TestCase
class LocalhostTestCase(TestCase):
    def setUp(self):
        sockfilter.enable(lambda x: (address.host in ['localhost', '127.0.0.1']))
    def tearDown(self):
        sockfilter.disable()
```

Here is the error.

```
celery_haystack.tasks.CeleryHaystackSignalHandler: ERROR: global name 'address' is not defined
Traceback (most recent call last):
  File "/var/www/django/venv/local/lib/python2.7/site-packages/celery_haystack/tasks.py", line 148, in run
    current_index.update_object(instance, **handler_options)
  File "/var/www/django/venv/local/lib/python2.7/site-packages/haystack/indexes.py", line 274, in update_object
    backend.update(self, [instance])
  File "/var/www/django/venv/local/lib/python2.7/site-packages/haystack/backends/elasticsearch_backend.py", line 183, in update
    self.conn.bulk_index(self.index_name, 'modelresult', prepped_docs, id_field=ID)
  File "/var/www/django/venv/local/lib/python2.7/site-packages/pyelasticsearch/client.py", line 92, in decorate
    return func(*args, query_params=query_params, **kwargs)
  File "/var/www/django/venv/local/lib/python2.7/site-packages/pyelasticsearch/client.py", line 622, in bulk_index
    query_params=query_params)
  File "/var/www/django/venv/local/lib/python2.7/site-packages/pyelasticsearch/client.py", line 92, in decorate
    return func(*args, query_params=query_params, **kwargs)
  File "/var/www/django/venv/local/lib/python2.7/site-packages/pyelasticsearch/client.py", line 422, in bulk
    query_params=query_params)
  File "/var/www/django/venv/local/lib/python2.7/site-packages/pyelasticsearch/client.py", line 255, in send_request
    raise exc.info
NameError: global name 'address' is not defined

```

Here's the source of pyelasticsearch/client.py: https://github.com/pyelasticsearch/pyelasticsearch/blob/7714cf9c3b9fd7b34010ed1f919d3fe53971f576/pyelasticsearch/client.py#L255

**Comment by rchrd2** [comment]
OH NO. I just realized it's MY code that has the issue. I fixed it with:

```
import sockfilter
from django.test import TestCase
class LocalhostTestCase(TestCase):
    def setUp(self):
        sockfilter.enable(lambda x: (x.host in ['localhost', '127.0.0.1']))
    def tearDown(self):
        sockfilter.disable()

```
